"""Second

Revision ID: d3c75cd0aaea
Revises: c8571065e4ed
Create Date: 2023-12-20 22:53:58.709641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3c75cd0aaea'
down_revision = 'c8571065e4ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('charityproject', 'invested_amount',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('donation', 'invested_amount',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('donation', 'invested_amount',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('charityproject', 'invested_amount',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
